version: "3.9"

services:
  laravel-mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: Whitenoisegym
      MYSQL_PASSWORD: Blade890@
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s

  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    depends_on:
      laravel-mysql:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DB_CONNECTION: mysql
      DB_HOST: laravel-mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: Whitenoisegym
      DB_PASSWORD: Blade890@
      CLOUDINARY_URL: cloudinary://395673266618914:QAEtxszJ3XxsG0JZltnX71U42TQ@dq10qlo0n
      CLOUDINARY_API_KEY: 395673266618914
      CLOUDINARY_API_SECRET: QAEtxszJ3XxsG0JZltnX71U42TQ
      CLOUDINARY_CLOUD_NAME: dq10qlo0n
    working_dir: /var/www/html
    volumes:
      # Only mount folders that need persistence, NOT public/build
      - .:/var/www/html
      - ./app:/var/www/html/app
      - ./bootstrap:/var/www/html/bootstrap
      - ./config:/var/www/html/config
      - ./database:/var/www/html/database
      - ./resources:/var/www/html/resources
      - ./routes:/var/www/html/routes
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - storage_data:/var/www/html/storage
    # healthcheck:
    #   test: ["CMD", "php", "-v"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3

  laravel-nginx:
    image: nginx:stable-alpine
    container_name: laravel-nginx
    restart: unless-stopped
    depends_on:
      - laravel-app
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  mysql_data:
  storage_data:
