version: "3.9"

services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
      CLOUDINARY_URL: cloudinary://395673266618914:QAEtxszJ3XxsG0JZltnX71U42TQ@dq10qlo0n
      CLOUDINARY_API_KEY: 395673266618914
      CLOUDINARY_API_SECRET: QAEtxszJ3XxsG0JZltnX71U42TQ
      CLOUDINARY_CLOUD_NAME: dq10qlo0n
    working_dir: /var/www/html
    volumes:
      # Only mount folders that need persistence, NOT public/build
      - .:/var/www/html
      - ./app:/var/www/html/app
      - ./bootstrap:/var/www/html/bootstrap
      - ./config:/var/www/html/config
      - ./database:/var/www/html/database
      - ./resources:/var/www/html/resources
      - ./routes:/var/www/html/routes
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - storage_data:/var/www/html/storage
    # healthcheck:
    #   test: ["CMD", "php", "-v"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3

  laravel-nginx:
    image: nginx:stable-alpine
    container_name: laravel-nginx
    restart: unless-stopped
    depends_on:
      - laravel-app
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  storage_data:
